apiVersion: v1
kind: Service
metadata:
  name: device-shop-server-nodeport
spec:
  type: NodePort
  selector:
    app: device-shop-server
  ports:
    - protocol: TCP
      port: 51234
      targetPort: 51234
      nodePort: 80  