name: Docker Build and Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push device-shop-client image
      run: |
        docker build -t device-shop-client ./device-shop-client
        docker tag device-shop-client ${{ secrets.DOCKER_USERNAME }}/device-shop:client
        docker push ${{ secrets.DOCKER_USERNAME }}/device-shop:client

    - name: Build and push device-shop-server image
      run: |
        docker build -t device-shop-server ./device-shop-server
        docker tag device-shop-server ${{ secrets.DOCKER_USERNAME }}/device-shop:server
        docker push ${{ secrets.DOCKER_USERNAME }}/device-shop:server

    - name: Build and push device-shop-session image
      run: |
        docker build -t device-shop-session ./device-shop-session
        docker tag device-shop-session ${{ secrets.DOCKER_USERNAME }}/device-shop:session
        docker push ${{ secrets.DOCKER_USERNAME }}/device-shop:session
